### ISSUE TITLE
Demo result looks bad

### ISSUE THREAD

**Issue by liuwenran** [salesforce/GlueGen#2]
by running this code
```shell
python scripts/txt2img.py --prompt "一只狗" --plms --outdir outputs/text2img-multilingual --ckpt ../checkpoints_all/checkpoint_sd_v1/v1-5-pruned-emaonly.ckpt --n_iter 1
```
the result image is not a dog.
![grid-0033一只狗](https://user-images.githubusercontent.com/12782558/236405239-30269e90-07e2-4e1c-ae47-70053678adc8.png)

**Comment by canqin001** [comment]
Please use `txt2img_demo_ml.py` #1. 

The results of `python scripts/txt2img_demo_ml.py --prompt "一只狗" --plms --outdir outputs/text2img-multilingual --ckpt ../checkpoints_all/checkpoint_sd_v1/v1-5-pruned-emaonly.ckpt --n_iter 1` look like this:

![grid-0001-一只狗](https://github.com/salesforce/GlueGen/assets/46471476/287d19ee-4559-499f-bbc7-bb7e2910a860)
